services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-zny!40=x_+$!&z5a7eew-9i2a+uj%j4udos4pr^9gpk+(8pa&y
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    command: python manage.py runserver 0.0.0.0:8000
