services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_ENGINE: postgres
      DB_NAME: fleema
      DB_USER: fleema
      DB_PASSWORD: fleema
      DB_HOST: db
      DB_PORT: "5432"
      DJANGO_DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: fleema
      POSTGRES_USER: fleema
      POSTGRES_PASSWORD: fleema
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: