version: '3.8'

services:
  web:
    container_name: Docker.felix
    build:
      context: ../
      dockerfile: felix/Dockerfile
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../:/app
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - db
    networks:
      - Docker.felix

  db:
    container_name: Docker.felix-postgres
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    networks:
      - Docker.felix

volumes:
  postgres_data:

networks:
  Docker.felix:
    driver: bridge
